version: "3"

services:
  postgres:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    environment:
      - POSTGRES_PASSWORD=postgres_password

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - COLLECTOR_HOST=collector
      - COLLECTOR_PORT=55681
      - APP_NAME=story_views_api
    volumes:
      - /api/node_modules
      - ./api/:/api
    ports:
      - "5000:5000"
    depends_on:
      - collector
      - postgres

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - collector
      - api

  collector:
    image: otel/opentelemetry-collector-contrib:0.27.0
    # FOR debugging purposes, insights of what the collector is doing
    # command: ["--config=/conf/collector-config.yaml", "--log-level=DEBUG"]
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./observability/collector/collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "55681:55681"
    depends_on:
      - jaeger-all-in-one

  jaeger-all-in-one:
    build:
      dockerfile: Dockerfile.dev
      context: ./observability/jaeger
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
