# define receivers, eg. otlp with supported protocols grpc, http
receivers:
  otlp:
    protocols:
      grpc:
      http:
        # USE FOR CORS
        # cors_allowed_origins:
        #   - http://*
        #   - https://*

# define exporters, eg. jaeger
# if you use logzio, define logzio
exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
  # UNCOMMENT after you setup a logzio account and get a logzio tracing token
  # logzio:
  #   account_token: "your-token"
  #   region: "your-region"

# define span processors
processors:
  batch:

# define services and pipelines for traces
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
      # OR use as exporters in case of logzio
      # exporters: [jaeger,logzio]
